### PR TITLE
fix: App does not crash

### LINKED ISSUE #45: App crashes at sign-in
First sign-in makes the app crash.

### PR DESCRIPTION
**Pull request by malenesoeholm**
The app does not crash at first connection laundry.

Closes #45

### CODE REVIEW

File: src/react/views/Timetable.js [hunk 1]
```diff
@@ -233,7 +233,7 @@ export default class TimetableWrapper extends React.Component {
   }
 
   componentWillMount () {
-    this.fetchData()
+    if (this.props.laundry) this.fetchData()
```
Comment (budde377) [inline src/react/views/Timetable.js]: You dont need this, since you are assuming that `props.laundry` is required

File: src/react/views/Timetable.js [hunk 2]
```diff
@@ -259,7 +259,7 @@ export default class TimetableWrapper extends React.Component {
   }
 
   render () {
-    if (!this.props.machines) {
+    if (!this.props.machines || !this.props.laundry) {
```
Comment (budde377) [inline src/react/views/Timetable.js]: Same ^^
